import requests
from bs4 import BeautifulSoup
import re
import os
from markdownify import markdownify as md

URL = "https://www.lua.org/manual/5.4/manual.html"
OUTPUT_FILE = "uczone-docs/lua_manual_5_4.md"

def fetch_and_parse():
    print(f"🚀 Fetching Lua 5.4 Manual from {URL}...")
    try:
        headers = {'User-Agent': 'Mozilla/5.0'}
        response = requests.get(URL, headers=headers)
        response.raise_for_status()
    except Exception as e:
        print(f"❌ Error fetching URL: {e}")
        return

    soup = BeautifulSoup(response.content, 'html.parser')

    # Remove non-content elements (scripts, styles, navs)
    for tag in soup(['script', 'style', 'nav', 'footer', 'iframe', 'form', 'link', 'meta']):
        tag.decompose()

    # Remove specific Lua manual navigation artifacts
    # (Lua.org manual usually has top/bottom nav links like "contents · index")
    for nav_text in soup.find_all(string=re.compile(r"contents\s+·\s+index")):
        if nav_text.parent:
            nav_text.parent.decompose()
            
    # The manual content is typically in the body.
    # We strip the footer which often contains "Last change..."
    for p in soup.find_all('p'):
        if 'Last change:' in p.get_text():
            p.decompose()

    print("🔄 Converting HTML to Markdown...")
    # Convert to Markdown using markdownify
    # heading_style="ATX" ensures # headers instead of underlines
    markdown_text = md(str(soup.body), heading_style="ATX")
    
    # Post-processing cleanup
    # 1. Remove excessive newlines
    markdown_text = re.sub(r'\n{3,}', '\n\n', markdown_text)
    
    # 2. Fix some common artifacts if necessary
    markdown_text = markdown_text.strip()
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    
    print(f"💾 Saving to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(f"<!-- Source: {URL} -->\n")
        f.write(f"<!-- Generated by fetch_lua_manual.py -->\n\n")
        f.write(markdown_text)
        
    print(f"✅ Successfully generated {OUTPUT_FILE} ({len(markdown_text)} chars)")

if __name__ == "__main__":
    fetch_and_parse()
