name: Update Documentation Date

on:
  push:
    paths:
      - 'DocumentationUCZONE.md'
    branches:
      - main
  workflow_dispatch:
  schedule:
    # 20:00 MSK is 17:00 UTC
    - cron: '0 17 * * *'

jobs:
  update-date:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Commit Date
        id: date
        run: |
          # Get the date of the last commit (HEAD)
          # Format: DD.MM.YYYY
          LAST_DATE=$(git show -s --format="%cd" --date=format:"%d.%m.%Y" HEAD)
          echo "NEW_DATE=$LAST_DATE" >> $GITHUB_ENV
          echo "Found date: $LAST_DATE"

      - name: Update Dates
        run: |
          # Update date in README.md (looks for "**Last Update**: DD.MM.YYYY")
          sed -i "s/\*\*Last Update\*\*: [0-9]\{2\}\.[0-9]\{2\}\.[0-9]\{4\}/**Last Update**: $NEW_DATE/g" README.md

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update last updated date to ${{ env.NEW_DATE }} [skip ci]"
          file_pattern: "README.md"